name: tests

on:
  push:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest suite
        run: python -m pytest

      - name: Collect code coverage
        run: python -m pytest --cov=. --cov-report=term-missing
